#!/bin/bash

SELF=$(readlink -f "$0")
HERE=${SELF%/*}

export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"

export COIN_DATA_DIR="${HERE}/usr/share/coin-counter/data"

export GTK_THEME=${GTK_THEME:-Adwaita}

export GTK_OVERLAY_SCROLLING=0

exec "${HERE}/usr/bin/coin_counter" "$@"
